# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.LoginButton = QtWidgets.QPushButton(self.centralwidget)
        self.LoginButton.setGeometry(QtCore.QRect(160, 390, 171, 81))
        self.LoginButton.setObjectName("LoginButton")
        self.RgisteredButton = QtWidgets.QPushButton(self.centralwidget)
        self.RgisteredButton.setGeometry(QtCore.QRect(430, 390, 171, 81))
        self.RgisteredButton.setObjectName("RgisteredButton")
        self.IDinsert = QtWidgets.QLineEdit(self.centralwidget)
        self.IDinsert.setGeometry(QtCore.QRect(140, 80, 521, 91))
        self.IDinsert.setObjectName("IDinsert")
        self.PassWordInsert = QtWidgets.QLineEdit(self.centralwidget)
        self.PassWordInsert.setGeometry(QtCore.QRect(140, 200, 521, 91))
        self.PassWordInsert.setObjectName("PassWordInsert")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 110, 101, 41))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 230, 101, 41))
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.LoginButton.setText(_translate("MainWindow", "登录"))
        self.RgisteredButton.setText(_translate("MainWindow", "注册"))
        self.label.setText(_translate("MainWindow", "账号"))
        self.label_2.setText(_translate("MainWindow", "密码"))
