# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'registration.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Registration(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.UserldEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.UserldEdit.setGeometry(QtCore.QRect(220, 80, 271, 61))
        self.UserldEdit.setObjectName("UserldEdit")
        self.UserPassEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.UserPassEdit.setGeometry(QtCore.QRect(220, 160, 271, 61))
        self.UserPassEdit.setObjectName("UserPassEdit")
        self.UserNameEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.UserNameEdit.setGeometry(QtCore.QRect(220, 240, 271, 61))
        self.UserNameEdit.setObjectName("UserNameEdit")
        self.AgeEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.AgeEdit.setGeometry(QtCore.QRect(220, 320, 271, 61))
        self.AgeEdit.setObjectName("AgeEdit")
        self.QQNumEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.QQNumEdit.setGeometry(QtCore.QRect(220, 400, 271, 61))
        self.QQNumEdit.setObjectName("QQNumEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 100, 81, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(80, 170, 81, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(80, 250, 81, 31))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(80, 340, 81, 31))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(80, 420, 81, 31))
        self.label_5.setObjectName("label_5")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(230, 490, 151, 51))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "账号"))
        self.label_2.setText(_translate("MainWindow", "密码"))
        self.label_3.setText(_translate("MainWindow", "用户名"))
        self.label_4.setText(_translate("MainWindow", "年龄"))
        self.label_5.setText(_translate("MainWindow", "qq"))
        self.pushButton.setText(_translate("MainWindow", "成功注册"))
